import os

class GameConfig:

    SCREEN_WIDTH = 1920
    SCREEN_HEIGHT = 1080
    FPS = 60


    SKY_BLUE = (135, 206, 235)
    GROUND_COLOR = (86, 125, 70)

    @staticmethod
    def asset_path(*paths):
        base_dir = os.path.dirname(os.path.dirname(os.path.dirname(__file__)))
        return os.path.join(base_dir, "assets", *paths)


    PLAYER_WIDTH = 233
    PLAYER_HEIGHT = 397
    PLAYER_SCALE = 0.5

    PLAYER_SPEED = 0
    JUMP_STRENGTH = -18
    GRAVITY = 0.8
    GROUND_LEVEL = 900


    CLOUD_COUNT = 8
    BACKGROUND_SCROLL_SPEED = 1.5
    GROUND_SCROLL_SPEED = 6.0
    CLOUD_SPEED = 0.5


    OBSTACLE_COUNT = 4
    OBSTACLE_SPAWN_RATE = 1800

    OBSTACLE_MIN_GAP = int(SCREEN_WIDTH * 0.10)
    OBSTACLE_MAX_GAP = int(SCREEN_WIDTH * 0.15)
    OBSTACLE_SPEED = 6.0


    PLAYER_TO_CACTUS_RATIO = 0.75
    PLAYER_TO_BIRD_RATIO = 0.55


    DEBUG_SHOW_COLLISIONS = False


    CACTUS_COUNT = 3

    CACTUS_WIDTH = int(PLAYER_WIDTH * PLAYER_TO_CACTUS_RATIO)
    CACTUS_HEIGHT = int(PLAYER_HEIGHT * PLAYER_TO_CACTUS_RATIO)


    BIRD_COUNT = 2

    BIRD_WIDTH = int(PLAYER_WIDTH * PLAYER_TO_BIRD_RATIO)
    BIRD_HEIGHT = int(PLAYER_HEIGHT * PLAYER_TO_BIRD_RATIO)





    BIRD_MIN_HEIGHT = int(GROUND_LEVEL - PLAYER_HEIGHT * 0.85)
    BIRD_MAX_HEIGHT = int(GROUND_LEVEL - PLAYER_HEIGHT * 0.35)


    SCORE_MULTIPLIER = 0.15
    HIGH_SCORE_FILE = "highscore.txt"


    GAME_SPEED_INCREASE = 0.00015
    INITIAL_GAME_SPEED = 1.0
    MAX_GAME_SPEED = 3.5


